### ISSUE TITLE
OSD for the hardware controls

### ISSUE THREAD

**Issue by rp1231** [applapp/EarTrumpet.HardwareSupportAddon#1]
Hi, I am a deej and eartrumpet user and have been waiting for something like this!
Would it be possible to have a volume mixer OSD popup every time you change volume?
I struggle to know the volume changes when I use hardware controls and an OSD  would be perfect!

Thanks for this.
Eagerly waiting for the official release.

**Comment by svenwml** [comment]
Ah sorry, we got no notification about your request and just saw the issue right now.
Thanks for testing our plugin and giving your feedback!
I already replied to the issue in the EarTrumpet main application project (https://github.com/File-New-Project/EarTrumpet/discussions/740) (right now I think this should be implemented in the main application). However, @skief and me will see if we maybe have the possibility to trigger an overlay from within the plugin.

**Comment by svenwml** [comment]
OSD is implemented now and will be part of the release. There are still some smaller things we will work on so there may be some slight changes in the future. The feature can be activated / deactivated and the position on the screen is configurable in the plugin options.

Thanks @davuxcom for the nice sample implementation and thanks @rp1231 for the suggestion!

![image](https://user-images.githubusercontent.com/69305180/109850046-5e86ff00-7c52-11eb-8680-d75926353e3a.png)
