### ISSUE TITLE
How do I build this?

### ISSUE THREAD

**Issue by rp1231** [applapp/EarTrumpet.HardwareSupportAddon#4]
Hi,

Doesn't seem like the new version of eartrumpet with the plugin system is going to be released soon.

Just wanted to ask how I can build this?

Thanks

**Comment by svenwml** [comment]
Hi @rp1231, sorry for the late response. Did you figure it out in the meantime?

We did some fixes and added a compiling instruction here: 

https://github.com/applapp/EarTrumpet.HardwareSupportAddon/blob/master/COMPILING.md

If you have any problems compiling, let us know.

**Comment by rp1231** [comment]
I had managed to build a version but couldn't find the addons options in the settings.....
It was like the standard version of eartrumpet.
I'll try it once more following the instructions and see if it works.

Thanks a lot.

**Comment by svenwml** [comment]
Yes, it seems that the plugin has not been loaded properly then. You should see a "Hardware Support" button next to the General preferences button in the EarTrumpet settings window.

**Comment by rp1231** [comment]
Thanks,
It worked!

**Comment by svenwml** [comment]
Perfect, thanks for the feedback :)
