### ISSUE TITLE
License

### ISSUE THREAD

**Issue by svenwml** [applapp/EarTrumpet.HardwareSupportAddon#5]
We would like to add a license to this project. The idea is to use the same license as for the EarTrumpet project (MIT): https://github.com/File-New-Project/EarTrumpet/blob/35f8eae3a2ec94ae32a46b4cdbfa264475aa7400/LICENSE

@davuxcom : Since you provided us with the initial addon package and also contributed to this project a lot of times we think it is best to ask you if you and the EarTrumpet developer team agree with choosing the MIT license for this addon?

Best regards

**Comment by davuxcom** [comment]
Seems reasonable to me! :)

**Comment by svenwml** [comment]
Thanks! License is added.
