### ISSUE TITLE
Offset doesn't work for the center position

### ISSUE THREAD

**Issue by rp1231** [applapp/EarTrumpet.HardwareSupportAddon#6]
Hi,
I tried the build out and it works great!
Just wanted to report that the offset parameters don't seem to be working when the center position is selected.
Thanks
![EarTrumpet_V72GrpsKL3](https://user-images.githubusercontent.com/47380919/153697123-da326d85-ff2a-4214-90aa-51c240f04838.png)

**Comment by svenwml** [comment]
Thanks for the report! Offsets were indeed not regarded in center position. Fixed in the latest commit.
